<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<AssemblyName>test</AssemblyName>
		<IsPackable>false</IsPackable>
		<LangVersion>preview</LangVersion>
		<TargetFramework>net11.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\library\library.csproj"/>
	</ItemGroup>

	<ItemGroup Condition="'$(PublishAot)' == 'true'">
		<DirectPinvoke Include="luajit"/>

		<NativeLibrary
			Include="$(LuaJitDir)luajit.lib"/>
	</ItemGroup>

	<ItemGroup Condition="'$(PublishAot)' != 'true'">
		<None
			Include="$(LuaJitDir)luajit.dll"
			CopyToOutputDirectory="PreserveNewest"/>
	</ItemGroup>
</Project>
